//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by surf.rc
//
#define IDD_ABOUTBOX                    100
#define ID_FULLSCREEN0                  102
#define ID_FULLSCREEN1                  103
#define ID_FULLSCREEN2                  104
#define ID_FULLSCREEN3                  105
#define ID_FULLSCREEN4                  106
#define ID_FULLSCREEN5                  107
#define ID_FULLSCREEN6                  108
#define ID_FULLSCREEN7                  109
#define ID_FULLSCREEN8                  110
#define ID_FULLSCREEN9                  111
#define ID_FULLSCREEN10                 112
#define ID_FULLSCREEN11                 113
#define ID_FULLSCREEN12                 114
#define ID_FULLSCREEN13                 115
#define ID_FULLSCREEN14                 116
#define ID_FULLSCREEN15                 117
#define ID_NETWORK0                     119
#define ID_NETWORK1                     120
#define ID_NETWORK2                     121
#define ID_NETWORK3                     122
#define ID_NETWORK4                     123
#define ID_NETWORK5                     124
#define ID_NETWORK6                     125
#define ID_NETWORK7                     126
#define ID_NETWORK8                     127
#define IDR_MAINFRAME                   128
#define ID_NETWORK9                     128
#define ID_NETWORK10                    129
#define ID_NETWORK11                    130
#define ID_NETWORK12                    131
#define ID_NETWORK13                    132
#define ID_NETWORK14                    133
#define ID_NETWORK15                    134
#define ID_DRIVER0                      135
#define ID_DRIVER1                      136
#define ID_DRIVER2                      137
#define ID_DRIVER3                      138
#define ID_DRIVER4                      139
#define ID_DRIVER5                      140
#define ID_DRIVER6                      141
#define ID_DRIVER7                      142
#define ID_DRIVER8                      143
#define ID_DRIVER9                      144
#define ID_DRIVER10                     145
#define ID_DRIVER11                     146
#define ID_DRIVER12                     147
#define ID_DRIVER13                     148
#define ID_DRIVER14                     149
#define ID_DRIVER15                     150
#define IDD_NET_CREATE                  156
#define IDD_NET_SEL_SESSION             157
#define IDD_NET_NAMES                   159
#define IDB_1947SPLASH                  167
#define IDR_WAVEMAP0                    183
#define IDR_WAVEMAP1                    184
#define IDR_WAVEMAP2                    185
#define IDR_WAVEMAP3                    186
#define IDR_WAVEMAP4                    187
#define IDR_WAVEMAP5                    188
#define IDR_WAVEMAP6                    189
#define IDR_WAVEMAP7                    190
#define IDR_LEFTWALLMAP                 191
#define IDR_RITEWALLMAP                 192
#define IDR_BEACHWALLMAP                193
#define IDR_UFOMAP                      194
#define IDR_CHOICEMIDI                  195
#define IDB_ALPHABET                    198
#define IDB_INTERSKY                    199
#define IDB_LOGONAV                     200
#define IDB_INTERFACE                   201
#define IDB_SPINSPEED                   202
#define IDB_SURFSKY                     203
#define IDR_ALANAYELLWAVE               204
#define IDR_SINKWAVE                    205
#define IDR_BUCKYYELLWAVE               206
#define IDR_LEEYELLWAVE                 207
#define IDR_SANDYYELLWAVE               208
#define IDR_TODDYELLWAVE                209
#define IDR_VICYELLWAVE                 210
#define IDR_OCEANWAVE                   211
#define IDR_GAMEOVERWAVE                212
#define IDR_SEAGULLWAVE                 213
#define IDR_SEAGULLWAVE1                213
#define IDR_SPLASHWAVE                  215
#define IDR_UFOWAVE                     216
#define IDR_GRUNTWAVE                   218
#define IDR_ALANAX                      220
#define IDR_BEACHWALLX                  221
#define IDR_BUCKYX                      222
#define IDR_LEEX                        223
#define IDR_LEFTWALLX                   224
#define IDR_WAVEX                       225
#define IDR_CURLX                       226
#define IDR_RITEWALLX                   227
#define IDR_SANDYX                      228
#define IDR_SPRAYX                      229
#define IDR_THEBEACHX                   230
#define IDR_TODDX                       231
#define IDR_UFOX                        232
#define IDR_VICX                        233
#define IDR_WAVEFRAME01X                235
#define IDR_WAVEFRAME02X                236
#define IDR_WAVEFRAME03X                237
#define IDR_WAVEFRAME04X                238
#define IDR_WAVEFRAME05X                239
#define IDR_WAVEFRAME06X                240
#define IDR_WAVEFRAME07X                241
#define IDR_WAVEFRAME08X                242
#define IDR_WAVEFRAME00X                243
#define IDR_ALANAMIDI                   244
#define IDR_BUCKYMIDI                   245
#define IDR_LOADMIDI                    246
#define IDR_CREDITSMIDI                 247
#define IDR_GAMEOVER1MIDI               248
#define IDR_GAMEOVER2MIDI               249
#define IDR_HISCOREMIDI                 250
#define IDR_VICMIDI                     251
#define IDR_LEEMIDI                     252
#define IDR_SANDYMIDI                   253
#define IDR_TODDMIDI                    254
#define IDR_FOAMMAP0                    255
#define IDR_FOAMMAP1                    256
#define IDR_FOAMMAP2                    257
#define IDR_FOAMMAP3                    259
#define IDR_FOAMMAP4                    261
#define IDR_FOAMMAP5                    262
#define IDR_FOAMMAP6                    263
#define IDR_FOAMMAP7                    264
#define IDR_DOLPHINX                    267
#define IDR_PIERX                       268
#define IDR_ROCKX                       269
#define IDR_BARRELX                     270
#define IDR_ALANAMAP                    271
#define IDR_BARRELMAP                   272
#define IDR_BUCKYMAP                    273
#define IDR_BUILDALLMAP                 274
#define IDR_LEEMAP                      275
#define IDR_SANDMAP                     276
#define IDR_SANDYMAP                    277
#define IDR_THATCHMAP                   278
#define IDR_HLXWALLMAP                  279
#define IDR_VANMAP                      280
#define IDR_SHUTTERMAP                  281
#define IDR_TIMMAP                      282
#define IDR_OPTIONSMAP                  283
#define IDR_OPTIONMAP                   283
#define IDR_SURFSIGNMAP                 284
#define IDR_WATERMAP                    285
#define IDR_FIRSTSIGNMAP                286
#define IDR_TODDMAP                     287
#define IDR_VICMAP                      288
#define IDR_SPRAYMAP0                   290
#define IDR_SPRAYMAP1                   291
#define IDR_SPRAYMAP2                   292
#define IDR_SPRAYMAP3                   293
#define IDR_SPRAYMAP4                   294
#define IDR_SPRAYMAP5                   295
#define IDR_SPRAYMAP6                   296
#define IDR_SPRAYMAP7                   297
#define IDR_LEFTBOUYX                   301
#define IDR_SHARKFINX                   303
#define IDR_SHARKHEADX                  304
#define IDR_RITEBOUYX                   306
#define IDR_180WAVE1                    308
#define IDR_180WAVE2                    309
#define IDR_360WAVE1                    310
#define IDR_360WAVE2                    311
#define IDR_540WAVE1                    312
#define IDR_540WAVE2                    313
#define IDR_720WAVE1                    314
#define IDR_720WAVE2                    315
#define IDR_900WAVE1                    316
#define IDR_900WAVE2                    317
#define IDR_DOUBLEINSANEWAVE1           320
#define IDR_DOUBLEINSANEWAVE2           321
#define IDR_TRIPLEINSANEWAVE1           322
#define IDR_TRIPLEINSANEWAVE2           323
#define IDR_QUADRUPLEINSANEWAVE1        324
#define IDR_QUADRUPLEINSANEWAVE2        325
#define IDR_SURFWAVE1                   328
#define IDR_SURFWAVE2                   329
#define IDR_SURFWAVE3                   330
#define IDR_BARRELWAVE                  331
#define IDR_BOUYWAVE                    332
#define IDR_UFOCWAVE                    333
#define IDR_ROCKWAVE                    335
#define IDR_PLIDWAVE                    336
#define IDR_POSTWAVE                    337
#define IDR_OUCHWAVE                    339
#define IDR_NEXTYEARWAVE                340
#define IDR_REEFWAVE1                   341
#define IDR_REEFWAVE2                   342
#define IDR_REEFWAVE                    342
#define IDR_REEFWAVE3                   343
#define IDR_UWONWAVE1                   344
#define IDR_UWONWAVE2                   345
#define IDR_MANGLEDWAVE                 346
#define IDR_HISCOREWAVE1                347
#define IDR_HISCOREWAVE2                348
#define IDR_BLOODMAP0                   358
#define IDR_BLOODMAP1                   359
#define IDR_BLOODMAP2                   360
#define IDR_BLOODMAP3                   361
#define IDR_BLOODMAP4                   362
#define IDR_BLOODMAP5                   363
#define IDR_PIERMAP                     364
#define IDR_ALANACDMIDI                 365
#define IDR_BUCKYCDMIDI                 366
#define IDR_LEECDMIDI                   367
#define IDR_SANDYCDMIDI                 368
#define IDR_TODDCDMIDI                  369
#define IDR_VICCDMIDI                   370
#define IDR_BOUYWAVE2                   375
#define IDR_ROCKWAVE2                   376
#define IDR_SHARKWAVE                   377
#define IDR_SHARKWAVE2                  379
#define IDR_BARRELWAVE2                 381
#define IDR_PLIDWAVE2                   382
#define IDR_POSTWAVE2                   383
#define IDR_STEAMSHIPWAVE               384
#define IDR_UFOSTOPWAVE                 385
#define IDR_DOLPHINWAVE                 386
#define IDR_DOLPHINWAVE2                387
#define IDB_LEROY                       391
#define IDD_LEROY                       392
#define IDB_LOGO                        394
#define IDB_NAV                         395
#define IDR_OILRIGX                     396
#define IDR_WRBEACHMAP                  398
#define IDB_ICONSNO                     399
#define IDB_ICONSYES                    400
#define IDR_TROPHYX                     401
#define IDR_BREAKHITWAVE1               402
#define IDR_BREAKHITWAVE2               403
#define IDR_TUBEWAVE                    405
#define IDR_DOLPHINHITWAVE1             406
#define IDR_DOLPHINHITWAVE2             407
#define IDR_OILRIGWAVE1                 408
#define IDR_OILRIGWAVE2                 409
#define IDR_OILLEGWAVE1                 410
#define IDR_OILLEGWAVE2                 411
#define IDR_ALANABAILWAVE               412
#define IDR_BUCKYBAILWAVE               413
#define IDR_LEEBAILWAVE                 414
#define IDR_SANDYBAILWAVE               415
#define IDR_TODDBAILWAVE                416
#define IDR_VICBAILWAVE                 417
#define IDR_LANDINGWAVE                 418
#define IDR_ALIENWAVE                   419
#define IDR_AMBULANCEWAVE               420
#define IDR_BARRELDAVEWAVE1             421
#define IDR_BARRELDAVEWAVE2             422
#define IDR_BLAMOWAVE                   423
#define IDR_DOLPHINDISTURBWAVE          424
#define IDR_GAMEOVERDAVEWAVE1           425
#define IDR_GAMEOVERDAVEWAVE2           426
#define IDR_GAMEOVERDAVEWAVE3           427
#define IDR_GROOVYTUBEWAVE1             428
#define IDR_GROOVYTUBEWAVE2             429
#define IDR_MUSTHURTWAVE                430
#define IDR_OHHWAVE1                    431
#define IDR_OHHWAVE2                    432
#define IDR_ORBITWAVE                   434
#define IDR_PIERACTIONWAVE              435
#define IDR_ROCKDAVEWAVE                436
#define IDR_SURFSCHOOLWAVE              437
#define IDR_SCREAMWAVE1                 438
#define IDR_SCREAMWAVE2                 439
#define IDR_SHARKDAVEWAVE1              440
#define IDR_SHARKDAVEWAVE2              441
#define IDR_UFODAVEWAVE1                442
#define IDR_UFODAVEWAVE2                443
#define IDR_WAGONWAVE                   444
#define IDR_WHAMOWAVE                   445
#define IDR_WIPEOUTWAVE1                446
#define IDR_WIPEOUTWAVE2                447
#define IDR_WIPEOUTWAVE3                448
#define IDR_WIPEOUTWAVE4                449
#define IDR_WUSSYWAVE                   450
#define IDR_TRICKWAVE1                  451
#define IDR_TRICKWAVE2                  452
#define IDR_TRICKWAVE3                  453
#define IDR_TRICKWAVE4                  454
#define IDR_TRICKWAVE5                  455
#define IDR_TRICKWAVE6                  456
#define IDR_TRICKWAVE7                  457
#define IDR_TRICKWAVE8                  458
#define IDR_TRICKWAVE9                  459
#define IDR_RIDICULOUSINSANEWAVE1       473
#define IDR_RIDICULOUSINSANEWAVE2       474
#define IDR_INSANEWAVE1                 475
#define IDR_INSANEWAVE2                 476
#define IDR_SLALOMWAVE                  477
#define IDR_WHOOSHWAVE                  478
#define IDR_CSGUYMAP                    479
#define IDR_HLGUYMAP                    480
#define IDR_SHOPGUYSX                   481
#define IDR_XTRAMIDS5                   482
#define IDR_BUCKYMIDS                   483
#define IDR_CHOICEMIDS2                 484
#define IDR_CHOICECONTESTMIDS2          485
#define IDR_CHOICECONTESTMIDS1          486
#define IDR_CHOICEMIDS1                 487
#define IDR_XTRAMIDS3                   488
#define IDR_LOADMIDS                    489
#define IDR_GAMEOVERMIDS1               490
#define IDR_GAMEOVERMIDS2               491
#define IDR_HISCOREMIDS2                492
#define IDR_HISCOREMIDS1                493
#define IDR_LEEMIDS                     494
#define IDR_SANDYMIDS                   495
#define IDR_TODDMIDS                    496
#define IDR_VICMIDS                     497
#define IDR_XTRAMIDS1                   498
#define IDR_XTRAMIDS2                   499
#define IDR_XTRAMIDS4                   500
#define IDR_ALANAMIDS                   501
#define IDR_MOUNTAINMAP                 504
#define IDR_SFLOGOMAP                   507
#define IDD_LOAD_PROGRESS               508
#define IDR_WIPEOUTWAVEA1               509
#define IDR_WIPEOUTWAVEA2               510
#define IDR_WIPEOUTWAVEA3               511
#define IDR_WIPEOUTWAVEA4               512
#define IDR_WIPEOUTWAVEB1               513
#define IDR_WIPEOUTWAVEB2               514
#define IDR_WIPEOUTWAVEB3               515
#define IDR_WIPEOUTWAVEB4               516
#define IDR_WIPEOUTWAVEL1               517
#define IDR_WIPEOUTWAVEL2               518
#define IDR_WIPEOUTWAVEL3               519
#define IDR_WIPEOUTWAVEL4               520
#define IDR_WIPEOUTWAVES1               521
#define IDR_WIPEOUTWAVES2               522
#define IDR_WIPEOUTWAVES3               523
#define IDR_WIPEOUTWAVET1               524
#define IDR_WIPEOUTWAVET2               525
#define IDR_WIPEOUTWAVEV1               526
#define IDR_WIPEOUTWAVEV2               527
#define IDR_WIPEOUTWAVEV3               528
#define IDR_WIPEOUTWAVEV4               529
#define IDR_TRICKWAVEA1                 530
#define IDR_TRICKWAVEA2                 531
#define IDR_TRICKWAVEA3                 532
#define IDR_TRICKWAVEB1                 533
#define IDR_TRICKWAVEB2                 534
#define IDR_TRICKWAVEB3                 535
#define IDR_TRICKWAVEL1                 540
#define IDR_TRICKWAVEL2                 541
#define IDR_TRICKWAVEL3                 542
#define IDR_TRICKWAVEL4                 543
#define IDR_TRICKWAVES1                 544
#define IDR_TRICKWAVES2                 545
#define IDR_TRICKWAVES3                 546
#define IDR_TRICKWAVES4                 547
#define IDR_TRICKWAVET1                 548
#define IDR_TRICKWAVET2                 549
#define IDR_TRICKWAVEV1                 550
#define IDR_TRICKWAVEV2                 551
#define IDR_TRICKWAVEV3                 552
#define IDR_HOLDWAVEA1                  553
#define IDR_HOLDWAVEA2                  554
#define IDR_360WAVEA1                   555
#define IDR_360WAVEA2                   556
#define IDR_TUBEWAVEA1                  557
#define IDR_TUBEWAVEA2                  558
#define IDR_DROPINWAVEA1                559
#define IDR_DROPINWAVEA2                560
#define IDR_DROPINWAVEA3                561
#define IDR_INSANITYWAVEA1              562
#define IDR_HOLDWAVEB1                  563
#define IDR_HOLDWAVEB2                  564
#define IDR_360WAVEB1                   565
#define IDR_360WAVEB2                   566
#define IDR_TUBEWAVEB1                  567
#define IDR_TUBEWAVEB2                  568
#define IDR_DROPINWAVEB1                569
#define IDR_DROPINWAVEB2                570
#define IDR_INSANITYWAVEB1              571
#define IDR_HOLDWAVEL1                  572
#define IDR_HOLDWAVEL2                  573
#define IDR_360WAVEL1                   574
#define IDR_360WAVEL2                   575
#define IDR_TUBEWAVEL1                  576
#define IDR_TUBEWAVEL2                  577
#define IDR_DROPINWAVEL1                578
#define IDR_DROPINWAVEL2                579
#define IDR_DROPINWAVEL3                580
#define IDR_INSANITYWAVEL1              581
#define IDR_INSANITYWAVEL2              582
#define IDR_HOLDWAVES1                  583
#define IDR_HOLDWAVES2                  584
#define IDR_360WAVES1                   585
#define IDR_360WAVES2                   586
#define IDR_TUBEWAVES1                  587
#define IDR_DROPINWAVES1                588
#define IDR_DROPINWAVES2                589
#define IDR_DROPINWAVES3                590
#define IDR_INSANITYWAVES1              591
#define IDR_HOLDWAVET1                  592
#define IDR_HOLDWAVET2                  593
#define IDR_360WAVET1                   594
#define IDR_360WAVET2                   595
#define IDR_TUBEWAVET1                  596
#define IDR_TUBEWAVET2                  597
#define IDR_DROPINWAVET1                598
#define IDR_DROPINWAVET2                599
#define IDR_INSANITYWAVET1              600
#define IDR_HOLDWAVEV1                  601
#define IDR_HOLDWAVEV2                  602
#define IDR_360WAVEV1                   603
#define IDR_360WAVEV2                   604
#define IDR_TUBEWAVEV1                  605
#define IDR_TUBEWAVEV2                  606
#define IDR_DROPINWAVEV1                607
#define IDR_DROPINWAVEV2                608
#define IDR_DROPINWAVEV3                609
#define IDR_INSANITYWAVEV1              610
#define IDR_RUNOVERWAVE1                611
#define IDR_USUREWAVE1                  612
#define IDR_ANBUCKYWAVE                 613
#define IDR_DISQUALIFYWAVE1             614
#define IDR_DISQUALIFYWAVE3             615
#define IDR_HEATOVERWAVE1               616
#define IDR_HEATOVERWAVE2               617
#define IDR_USUREWAVE2                  618
#define IDR_ANLEEWAVE                   619
#define IDR_RUNOVERWAVE2                620
#define IDR_ANSANDYWAVE                 621
#define IDR_ANTODDWAVE                  622
#define IDR_ANALANAWAVE                 623
#define IDR_ANVICWAVE                   624
#define IDR_DISQUALIFYWAVE2             625
#define IDR_SEAGULLWAVE2                626
#define IDR_TRICKWAVE10                 627
#define IDR_UWONWAVE                    628
#define IDD_TRACKS                      629
#define IDB_VLAACHOS                    630
#define IDD_SHAREEXIT                   632
#define IDB_SHAREEXIT                   634
#define IDD_GAMESPEED                   636
#define ID_START_SESSION                1003
#define ID_JOIN_SESSION                 1004
#define IDC_SESSION_NAME                1005
#define IDC_PLAYER_NAME                 1006
#define IDC_TIME                        1009
#define IDC_LIFE                        1010
#define IDC_SCORE                       1011
#define IDC_UFO                         1012
#define IDC_STATSUP                     1013
#define IDC_CHEATKEYS                   1013
#define IDC_NAVMODE                     1015
#define IDC_TEXT                        1015
#define IDC_TRON                        1016
#define IDC_GRAPH                       1016
#define IDC_SPLASH_LOGO                 1017
#define IDC_LEROY_IMAGE                 1018
#define IDC_LB_SESSION                  1024
#define IDC_LEROY_FACE                  1051
#define IDC_VLAACHOS                    1052
#define IDC_CHECK1                      1076
#define IDC_CHECK2                      1077
#define IDC_CHECK3                      1078
#define IDC_CHECK4                      1079
#define IDC_CHECK5                      1080
#define IDC_CHECK6                      1081
#define IDC_CHECK7                      1082
#define IDC_CHECK8                      1083
#define IDC_CHECK9                      1084
#define IDC_CHECK10                     1085
#define IDC_CHECK11                     1086
#define IDC_CHECK12                     1087
#define IDC_CHECK13                     1088
#define IDC_CHECK14                     1089
#define IDC_CHECK15                     1090
#define IDC_CHECK16                     1091
#define IDC_CHECK17                     1092
#define IDC_CHECK18                     1093
#define IDC_CHECK19                     1094
#define IDC_CHECK20                     1095
#define IDC_CHECK21                     1096
#define IDC_RADIOFPS10                  1102
#define IDC_RADIOFPS12                  1104
#define IDC_RADIOFPS14                  1105
#define IDC_RADIOFPS16                  1106
#define IDC_RADIOFPS22                  1107
#define IDC_RADIOFPS8                   1108
#define IDC_RADIOFPS20                  1109
#define IDC_RADIOFPS18                  1110
#define IDC_SPEEDSLIDER                 1111
#define IDI_SURF                        31234
#define ID_SPEEDOMETER_TOGGLE           32772
#define ID_DETAILS_MAXFRAMERATE_XFPS    32793
#define ID_HALFRES                      32813
#define ID_TRONMODE                     32814
#define ID_SPRAY                        32815
#define ID_SKYMAP                       32816
#define ID_BREAKINGWAVE                 32817
#define ID_WAVE_TEXTURES                32818
#define ID_MAIN_CAMERA                  32819
#define ID_HELICOPTER_CAMERA            32820
#define ID_TUBE_CAMERA                  32821
#define ID_BEACH_CAMERA                 32822
#define ID_SATELLITE_CAMERA             32823
#define ID_ROCK_VIDEO_CAMERA            32824
#define ID_SAVE_PLAYBACK                32825
#define ID_LOAD_PLAYBACK                32826
#define ID_PLAY_PLAYBACK                32827
#define ID_FPS                          32829
#define ID_BEGIN_CAPTURE                32831
#define ID_STOP_CAPTURE                 32832
#define ID_VIEW_HISCORES                32833
#define ID_UFO                          32834
#define ID_BREAK_NETWORK                32836
#define ID_HORIZON                      32838
#define ID_SAVE_SESSION                 32839
#define ID_LIST_PLAYERS                 32840
#define ID_LOAD_SESSION                 32841
#define ID_NAVIGATION                   32842
#define ID_MIDI_MUSIC                   32843
#define ID_CD_MUSIC                     32844
#define ID_SOUND_FX                     32845
#define ID_FOAM                         32846
//#define ID_HELPF                        32847
#define ID_AUTO_CAMERA                  32848
#define ID_NARATION                     32849
#define ID_GORE                         32850
#define ID_PRACTICE                     32851
#define ID_BEACH_CAMERA2                32852
#define ID_SURFER_SOUNDS                32853
#define ID_GAMESPEED                    32861
#define ID_TEXTURE_FILTER               32863
#define ID_SCORETOGGLE                  32864
#define ID_SHOW_ERRORS                  32865

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        644
#define _APS_NEXT_COMMAND_VALUE         32866
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           151
#endif
#endif
